# Site settings
author: Michael Waldo
title: Once I heard about coding I was "Audi".
header-img: img/home-bg.png
email: mbwcogic@yahoo.com
copyright_name: Michael Waldo
description: > # this means to ignore newlines until "baseurl:"
  One conversation changed my life. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mbwcogic

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
